config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  get '/home/about' => 'users#about', as: "about"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :books

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:home, :about]
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit]#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  def correct_user
    book = Book.find(params[:id])
    if current_user.id != book.user_id
      redirect_to books_path
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @new = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    if @book.save
      flash[:notice] = "Book was created successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was updated successfully"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource)
  #   about_path(resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    NotificationMailer.complete_mail(@user).deliver_now
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit]
  def correct_user
    user = User.find(params[:id])
    if current_user.id != user.id
      redirect_to user_path(current_user)
    end
  end

  def home
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User info was successfully updated"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Editing Book</h1>
  <%= render 'partial/error_msg', obj: @book %>
  <%= form_for @book do |f| %>
  <div class="field row">
  <%= f.label :title, "Title" %>
  <%= f.text_field :title, value: @book.title, class: "col-xs-12 book_title" %>
  </div>
  <div class="field row">
  <%= f.label :body, "Opinion" %>
  <%= f.text_area :body, value: @book.body, class: "col-xs-12 book_body" %>
  </div>
  <div class="actions row">
  <%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
  </div>
  <% end %>
  <%= link_to "Show", book_path(params[:id]) %>
  |
  <%= link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'partial/error_msg', obj: @book %>
<%= render 'partial/userinfo', book: @book, user: current_user%>
<div class="col-xs-9">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user_id) do %>
          <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book) do %>
          <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/books/show.html.erb
<%= render 'partial/userinfo', book: @new, user: @user %>
<div class="col-xs-9">
  <h2>Book detail</h2>
    <table class="table">
      <tbody>

        <% if current_user.id == @user.id %>
          
        <tr>
          <td>
          <%= link_to user_path(@user) do %>
          <%= attachment_image_tag @book.user, :profile_image, size: "100x100", fallback: "no_image.jpg" %>
          <br>
          <%= @user.name %>
          <% end %>
          </td>
          <td>
          <%= link_to book_path(params[:id]) do %>
          <%= @book.title %>
          <% end %>
          </td>
          <td><%= @book.body %></td>
          <td>
            <%= link_to "Edit", edit_book_path(params[:id]), class: "btn-sm btn-success" %>
          </td>
          <td>
            <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
          </td>
        </tr>
        <% else %>
        <tr>
          <td>
          <%= link_to user_path(@user) do %>
          <%= attachment_image_tag @book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
          <br>
          <%= @user.name %>
          <% end %>
          </td>
          <td>
          <%= link_to book_path(params[:id]) do %>
          <%= @book.title %>
          <% end %>
          </td>
          <td><%= @book.body %></td>
        </tr>

        <% end %>

      </tbody>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left"><span>Bookers</span></nav>
        <nav class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li>
            <%= link_to user_path(current_user.id) do %>
              <span class="glyphicon glyphicon-home home" aria-hidden="true"> Home</span>
            <% end %>
            </li>
            <li>
            <%= link_to users_path do %>
              <span class="glyphicon glyphicon-user users" aria-hidden="true"> Users</span>
            <% end %>
            </li>
            <li>
            <%= link_to books_path do %>
              <span class="glyphicon glyphicon-book books" aria-hidden="true"> Books</span>
            <% end %>
            </li>
            <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out logout" aria-hidden="true"> logout</span>
            <% end %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
            <%= link_to '/' do %>
              <span class="glyphicon glyphicon-home home" aria-hidden="true"> Home</span>
            <% end %>
            </li>
            <li>
            <%= link_to about_path do %>
              <span class="glyphicon glyphicon-link about" aria-hidden="true"> About</span>
            <% end %>
            </li>
            <li>
            <%= link_to new_user_registration_path do %>
              <span class="glyphicon glyphicon-edit sign_up" aria-hidden="true"> sign up</span>
            <% end %>
            </li>
            <li>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in login" aria-hidden="true"> login</span>
            <% end %>
            </li>
          </ul>
        <% end %>
        </nav>
      </div>
    </header>
    <div class="body">
      <div class="container">
        <p id="notice"><%= notice %></p>
          <div class="row">
          <%= yield %>
          </div>
          <div class="row">
            <div class="col-xs-3 col-xs-offset-9"><p>CpoyRight Infratop.inc</p></div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/partial/_error_msg.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation" >
    <h3><%= obj.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>  

app/views/partial/_userinfo.html.erb
<div class="col-xs-3">
  <h2>User info</h2>
  <div>
      <div>
        <%= attachment_image_tag user, :profile_image, size: "100x100", class: ".attachment user profile_image fallback", fallback: "no_image.jpg" %>
      </div>
      <div>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
          </tbody>
        </table>
      </div>
  </div>
  <div class="row">
  <% if user.id == current_user.id %>
    <%= link_to edit_user_path(user.id) do %>
      <span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" aria-hidden="true"></span>
    <% end %>
  <% else %>
    <%= link_to user_path(current_user.id) do %>
      <span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" aria-hidden="true"></span>
    <% end %>
  <% end %>
  </div>

  <div>
    <h2>New book</h2>
    <div>
      <%= form_for book, url: {controller: "books", action: "create"}, class: 'new_book', id: 'new_book' do |f| %>
      <div class="field row">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, value: '', id: 'book_title', class: 'col-xs-12 book_title' %>
      </div>
      <div class="field row">
        <%= f.label :body, "Opinion" %>
        <%= f.text_area :body, value: '', id: 'book_body', class: 'col-xs-12 book_body' %>
      </div>
      <div class="actions row">
        <%= f.submit "Create Book", class: 'btn btn-primary col-xs-12' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/about.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>!</h1>

app/views/users/edit.html.erb
  <h2>User info</h2>
  <%= render 'partial/error_msg', obj: @user %>
  <%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: "name" %>
  </div>

  <div class="field">
    <%= f.label :profile_image, "Image" %>
    <%= f.attachment_field :profile_image, class: "user_image" %>
  </div>

  <div class="field">
    <%= f.label :introduction, "Introduction" %>
    <%= f.text_area :introduction, rows:'2', class: "introduction" %>
  </div>

  <div class="actions">
    <%= f.submit "Update User" %>
  </div>
    
  <% end %>

app/views/users/home.html.erb
  <div class="row">
    <div class="top-message col-md-offset-3 col-md-6">
      <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers   !!</strong></span></h1>

      <p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="row"><%= link_to "Log in", new_user_session_path, class: 'btn btn-info col-xs-10 col-xs-offset-1 sign_in' %></div>
      <div class="row">
        <% if user_signed_in? %>
          <%= link_to "Sign Up", user_path(current_user), class: 'btn btn-success col-xs-10 col-xs-offset-1 sign_up' %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success col-xs-10 col-xs-offset-1 sign_up' %>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<%= render 'partial/userinfo', book: @book, user: current_user %>
<div class="col-xs-9">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user , :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "sign_in" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "sign_up" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= render 'partial/userinfo', book: @book, user: @user %>
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
        <%= link_to user_path(book.user_id) do %>
          <%= attachment_image_tag book.user, :profile_image, size: '50x50', fallback: "no_image.jpg" %>
        <% end %>
        </td>
        <td>
        <%= link_to book_path(book.id) do %>
          <%= book.title %>
        <% end %>
        </td>
        <td><%= book.body %></td>
        <td></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>